def printMenu():
  print("-"*40)
  print("Vuelos Duoc")
  print("-"*40)
  print("1.   Ver asientos disponibles")
  print("2.   Comprar asiento")
  print("3.   Anular vuelo")
  print("4.   Modificar datos de pasajero")
  print("5.   Salir")
  print("-"*40)
  print("Ingrese el numero de la función que desea utilizar")